#!/bin/bash
#  eiger2cbf_par  Script to run eiger2cbf in parallel
#  (c) Copyright 2017 Herbert J. Bernstein 
#      yayahjb@gmail.com, 12 Feb 2017
#
#  Covered by CBFlib licenses:  lgpl and gpl

######################################################################
#                                                                    #
# YOU MAY REDISTRIBUTE THE eiger2cbf_par UNDER THE TERMS OF THE GPL  #
#                                                                    #
# ALTERNATIVELY YOU MAY REDISTRIBUTE THE eiger2cbf_par API UNDER THE #
# TERMS OF THE LGPL                                                  #
#                                                                    #
######################################################################

########################### GPL NOTICES ##############################
#                                                                    #
# This program is free software; you can redistribute it and/or      #
# modify it under the terms of the GNU General Public License as     #
# published by the Free Software Foundation; either version 2 of     #
# (the License, or (at your option) any later version.               #
#                                                                    #
# This program is distributed in the hope that it will be useful,    #
# but WITHOUT ANY WARRANTY; without even the implied warranty of     #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the      #
# GNU General Public License for more details.                       #
#                                                                    #
# You should have received a copy of the GNU General Public License  #
# along with this program; if not, write to the Free Software        #
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA           #
# 02111-1307  USA                                                    #
#                                                                    #
######################################################################

######################### LGPL NOTICES ###############################
#                                                                    #
# This library is free software; you can redistribute it and/or      #
# modify it under the terms of the GNU Lesser General Public         #
# License as published by the Free Software Foundation; either       #
# version 2.1 of the License, or (at your option) any later version. #
#                                                                    #
# This library is distributed in the hope that it will be useful,    #
# but WITHOUT ANY WARRANTY; without even the implied warranty of     #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  #
# Lesser General Public License for more details.                    #
#                                                                    #
# You should have received a copy of the GNU Lesser General Public   #
# License along with this library; if not, write to the Free         #
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,    #
# MA  02110-1301  USA                                                #
#                                                                    #
######################################################################

masterfile=$1  #path to the desired master file
if [ "$masterfile" == "--help" ]
  then
  echo "eiger2cbf_par masterfile first_frame last_frame cbfout"
  echo "  masterfile -- the master h5 file with the metadata and links to the data"
  echo "  first_frame last_frame  -- frames numbered from 1"
  echo "  cbfout -- the name of the cbf file without the frame number"
  echo "            and without the .cbf extension"
  echo "generates parallel copies of eiger2cbf in blocks of 40 images for more"
  echo "than 999 frames, blocks of 20 for more than 199 frames, blocks of"
  echo "5 for more than 9 frames, and blocks of 1 otherwise" 
  exit
else

first_frame=$2 #first frame in the set
last_frame=$3  #last frame in the set
cbfout=$4      #cbf file name to write without the .cbf
#echo masterfile $masterfile
#echo first_frame:last_frame ${first_frame}:${last_frame}
iframe=$first_frame
nframes=`expr $last_frame - $first_frame + 1`
echo nframes $nframes
block_size=40
if [ $nframes -lt 1000 ]
  then block_size=20
fi
if [ $nframes -lt 200 ]
  then block_size=5
fi
if [ $nframes -lt 10 ]
  then block_size=1
fi
echo block_size $block_size

while [ $iframe -le $last_frame ]; do
  block_end=`expr $iframe + $block_size - 1`
  if [ $block_end -gt $last_frame ]
    then block_end=$last_frame
  fi
  eiger2cbf $masterfile $iframe:$block_end $cbfout >>/tmp/eiger2cbf_par_$$ 2>&1 &
  iframe=`expr $block_end + 1`
done
wait
sort -u  /tmp/eiger2cbf_par_$$
rm -rf /tmp/eiger2cbf_par_$$
fi
